services:
  - type: web
    name: chzzk-overlay-server
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: CHZZK_CLIENT_ID
        sync: false
      - key: CHZZK_CLIENT_SECRET
        sync: false
      - key: CHZZK_CHANNEL_ID
        sync: false
      - key: CHZZK_ACCESS_TOKEN
        sync: false
      - key: CHZZK_REFRESH_TOKEN
        sync: false
